// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ7I740or9Oc6Yc12QiK3oCv0DFDEiCv8',
    appId: '1:509186990141:web:af04b5c5666e201fe6ca54',
    messagingSenderId: '509186990141',
    projectId: 'chat-app-test-c9013',
    authDomain: 'chat-app-test-c9013.firebaseapp.com',
    storageBucket: 'chat-app-test-c9013.appspot.com',
    measurementId: 'G-G1ZCLD32GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6htEXhLbMNSdtOCdilo5I0T5A3jDQ9_E',
    appId: '1:509186990141:android:269a0a733c1ac169e6ca54',
    messagingSenderId: '509186990141',
    projectId: 'chat-app-test-c9013',
    storageBucket: 'chat-app-test-c9013.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDAdF20kDk5onyaI7ae6XX4IpxQxwflA0',
    appId: '1:509186990141:ios:e5c2557cbd436a96e6ca54',
    messagingSenderId: '509186990141',
    projectId: 'chat-app-test-c9013',
    storageBucket: 'chat-app-test-c9013.appspot.com',
    iosClientId: '509186990141-nv1cpgjm4c7rovf87reim4v0nlmls7eo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppTest',
  );
}
